---
dev_name: elasticsearch-dev
latest_release_filename: "/Users/benjaminguttmann/Documents/cf_ops/Trainings/CFSummitFFM/bosh_releases/elasticsearch/dev_releases/elasticsearch-dev/elasticsearch-dev-0+dev.36.yml"
